Config = Config or {}
Config.debug = false
Config.framework = 'qbx' -- qb, qbx (need to change the export on the Config.core)
Config.core = exports['qb-core']:GetCoreObject() -- Your core export (for qb is exports['qb-core']:GetCoreObject())
Config.inventory = 'ox_inventory' -- Your inventory script (qb-inventory, ox_inventory, ...)
Config.clothing = 'illenium-appearance' -- Your clothing menu script (qb-clothing, illenium-appearance, ...)

Config.locale = 'en' 

Config.hideRadar = true -- set to true if you want your minimap radar to be disabled when on multicharacter
Config.spawnLastLocation = true -- set to true if you want this to ignore the spawn selector and spawn directly at the last location
Config.startingApartment = false -- set this to true if you want your players to have default apartments
Config.enableDeleteButton = false -- set this to true if you want your players to be able to delete the characters
Config.defaultNumberOfCharacters = 5 -- this is the max default characters that players will have by default
Config.licenseType = 'license2' 

Config.defaultSpawn = vec4(-540.58, -212.02, 37.65, 208.88) -- this is the default spawn location if not using default apartments

Config.playersNumberOfCharacters = { -- here you'll add as many extra chars as you want for your players, follow the example
    ['license2:xxxxxxxxxxxxxxxxx'] = 10,
}

Config.logoutCommand = { command = 'logout', perm = 'group.admin' } -- command to logout of character

Config.starterItems = { -- the list of default items that a new player will spawn with
    { name = 'phone', amount = 1 },
    { name = 'id_card', amount = 1 },
    { name = 'driver_license', amount = 1 },
}

Config.locations = { -- char locations on multichar, it'll random
    {
        pedCoords = vec4(-811.7, 175.16, 76.75, 115.03),
        camCoords = vec4(-814.0, 173.68, 77.12, 295.03),
        hiddenCoords = vec4(-815.36, 180.01, 76.75, 186.96),
    }
}

Config.emotes = { -- list of emotes, the emote script can be changed at the client/functions.lua, it'll be playing a random emote
    'pose3',
    'smoke3',
    'wait'
}

Config.nationalities = { -- all the nationalities strings list
    "Afghan",
    "Albanian",
    "Algerian",
    "American",
    "Andorran",
    "Angolan",
    "Antiguan and Barbudan",
    "Argentine",
    "Armenian",
    "Australian",
    "Austrian",
    "Azerbaijani",
    "Bahamian",
    "Bahraini",
    "Bangladeshi",
    "Barbadian",
    "Belarusian",
    "Belgian",
    "Belizean",
    "Beninese",
    "Bhutanese",
    "Bolivian",
    "Bosnian",
    "Botswanan",
    "Brazilian",
    "British",
    "Bruneian",
    "Bulgarian",
    "Burkinabé",
    "Burmese",
    "Burundian",
    "Cabo Verdean",
    "Cambodian",
    "Cameroonian",
    "Canadian",
    "Central African",
    "Chadian",
    "Chilean",
    "Chinese",
    "Colombian",
    "Comoran",
    "Congolese (Congo-Brazzaville)",
    "Congolese (Congo-Kinshasa)",
    "Costa Rican",
    "Croatian",
    "Cuban",
    "Cypriot",
    "Czech",
    "Danish",
    "Djiboutian",
    "Dominican",
    "Dominican (Dominican Republic)",
    "Dutch",
    "East Timorese",
    "Ecuadorean",
    "Egyptian",
    "Emirati",
    "Equatorial Guinean",
    "Eritrean",
    "Estonian",
    "Ethiopian",
    "Fijian",
    "Filipino",
    "Finnish",
    "French",
    "Gabonese",
    "Gambian",
    "Georgian",
    "German",
    "Ghanaian",
    "Greek",
    "Grenadian",
    "Guatemalan",
    "Guinea-Bissauan",
    "Guinean",
    "Guyanese",
    "Haitian",
    "Honduran",
    "Hungarian",
    "Icelandic",
    "Indian",
    "Indonesian",
    "Iranian",
    "Iraqi",
    "Irish",
    "Israeli",
    "Italian",
    "Ivorian",
    "Jamaican",
    "Japanese",
    "Jordanian",
    "Kazakh",
    "Kenyan",
    "Kiribati",
    "Kuwaiti",
    "Kyrgyz",
    "Lao",
    "Latvian",
    "Lebanese",
    "Lesotho",
    "Liberian",
    "Libyan",
    "Liechtenstein",
    "Lithuanian",
    "Luxembourgish",
    "Macedonian",
    "Malagasy",
    "Malawian",
    "Malaysian",
    "Maldivian",
    "Malian",
    "Maltese",
    "Marshallese",
    "Mauritanian",
    "Mauritian",
    "Mexican",
    "Micronesian",
    "Moldovan",
    "Monacan",
    "Mongolian",
    "Montenegrin",
    "Moroccan",
    "Mozambican",
    "Namibian",
    "Nauruan",
    "Nepalese",
    "New Zealander",
    "Nicaraguan",
    "Nigerian",
    "Nigerien",
    "North Korean",
    "Norwegian",
    "Omani",
    "Pakistani",
    "Palauan",
    "Palestinian",
    "Panamanian",
    "Papua New Guinean",
    "Paraguayan",
    "Peruvian",
    "Polish",
    "Portuguese",
    "Qatari",
    "Romanian",
    "Russian",
    "Rwandan",
    "Saint Kitts and Nevis",
    "Saint Lucian",
    "Saint Vincent and the Grenadines",
    "Samoan",
    "San Marinese",
    "Sao Tomean",
    "Saudi",
    "Senegalese",
    "Serbian",
    "Seychellois",
    "Sierra Leonean",
    "Singaporean",
    "Slovak",
    "Slovenian",
    "Solomon Islander",
    "Somali",
    "South African",
    "South Korean",
    "South Sudanese",
    "Spanish",
    "Sri Lankan",
    "Sudanese",
    "Surinamese",
    "Swazi",
    "Swedish",
    "Swiss",
    "Syrian",
    "Tajik",
    "Tanzanian",
    "Thai",
    "Togolese",
    "Tongan",
    "Trinidadian and Tobagonian",
    "Tunisian",
    "Turkish",
    "Turkmen",
    "Tuvaluan",
    "Ugandan",
    "Ukrainian",
    "Uruguayan",
    "Uzbek",
    "Vanuatuan",
    "Venezuelan",
    "Vietnamese",
    "Yemeni",
    "Zambian",
    "Zimbabwean"
}